name: Publish Market Sentiment Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    # - cron: '0 */4 * * *' # 4-hour cadence option

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feed
        env:
          CRYPTOPANIC_TOKEN: ${{ secrets.CRYPTOPANIC_TOKEN }}
        run: |
          python cli.py --window 1h

      - name: Copy files to root for GitHub Pages
        run: |
          cp public/feed.json .
          cp public/history.json .

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/feed.json public/history.json feed.json history.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(feed): update feed.json [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Ensure feed exists
        run: |
          test -f public/feed.json
          test -f feed.json 